# Default configuration for CSV handling
csv_path: "candidates.csv"           # Path where CSV will be saved
fields:
  - name
  - email
  - phone
  - linkedin
  - subject
  - sender
  - received_date
  - notes
  - cv
duplicate_check_field: "email"        # Field used to detect duplicates
delimiter: ","                        # CSV delimiter
encoding: "utf-8"                     # CSV file encoding
# NOTE: You can extend fields or change the delimiter if needed
